# Generated by Django 6.0.6 on 2026-07-04 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('roads', 'Roads'), ('street_lights', 'Street Lights'), ('garbage', 'Garbage'), ('water', 'Water'), ('sewage', 'Sewage'), ('electricity', 'Electricity'), ('parks', 'Parks'), ('noise', 'Noise'), ('other', 'Other')], db_index=True, max_length=50)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('municipality', models.CharField(max_length=255)),
                ('ward_number', models.PositiveIntegerField()),
                ('address', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=20)),
                ('ai_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('flagged', 'Flagged')], db_index=True, default='pending', max_length=20)),
                ('visibility', models.BooleanField(default=True)),
                ('progress_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reports.report')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='reports.report')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['citizen', 'status'], name='reports_rep_citizen_cc7d61_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['municipality', 'ward_number'], name='reports_rep_municip_b2ac4e_idx'),
        ),
    ]
