# Generated by Django 6.0.6 on 2026-07-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='moderation_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
