# Generated by Django 6.0.6 on 2026-07-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notice',
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('COMMENT', 'Comment'), ('UPVOTE', 'Upvote'), ('STATUS_UPDATE', 'Status Update'), ('PROGRESS_UPDATE', 'Progress Update')], max_length=20),
        ),
    ]
