# Generated by Django 6.0.6 on 2026-07-05 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_adjust_model_for_phase_4_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('COMMENT', 'Comment'), ('UPVOTE', 'Upvote'), ('STATUS_UPDATE', 'Status Update'), ('PROGRESS_UPDATE', 'Progress Update'), ('NOTICE', 'Notice')], max_length=20),
        ),
    ]
