# Generated by Django 6.0.6 on 2026-07-04 22:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['municipality'], name='reports_rep_municip_67923f_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['ward_number'], name='reports_rep_ward_nu_b70abe_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['visibility'], name='reports_rep_visibil_4b4ca5_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['updated_at'], name='reports_rep_updated_b54274_idx'),
        ),
    ]
