# Generated by Django 6.0.6 on 2026-07-05 02:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_reports_rep_municip_67923f_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='reportvideo',
            name='video',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='video'),
        ),
    ]
