# Generated by Django 6.0.6 on 2026-07-06 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_modify_media_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], db_index=True, default='open', max_length=20),
        ),
    ]
